// Static metadata for the screener universe.
// Sector/industry never changes; beta is approximate.
// Live price data (P/E, market cap, etc.) comes from Yahoo Finance at runtime.

export interface StockMeta {
  sector: string;
  industry: string;
  country: string;
  beta: number;
}

export const STOCK_META: Record<string, StockMeta> = {
  // Mega cap
  AAPL:  { sector: 'Technology',            industry: 'Consumer Electronics',          country: 'United States', beta: 1.24 },
  MSFT:  { sector: 'Technology',            industry: 'Software—Infrastructure',       country: 'United States', beta: 0.90 },
  NVDA:  { sector: 'Technology',            industry: 'Semiconductors',                country: 'United States', beta: 1.98 },
  AMZN:  { sector: 'Consumer Cyclical',     industry: 'Internet Retail',               country: 'United States', beta: 1.15 },
  GOOGL: { sector: 'Communication Services',industry: 'Internet Content & Information',country: 'United States', beta: 1.06 },
  GOOG:  { sector: 'Communication Services',industry: 'Internet Content & Information',country: 'United States', beta: 1.06 },
  META:  { sector: 'Communication Services',industry: 'Internet Content & Information',country: 'United States', beta: 1.30 },
  TSLA:  { sector: 'Consumer Cyclical',     industry: 'Auto Manufacturers',            country: 'United States', beta: 2.38 },
  'BRK-B': { sector: 'Financial Services', industry: 'Insurance—Diversified',          country: 'United States', beta: 0.88 },

  // Large cap tech
  AVGO:  { sector: 'Technology',  industry: 'Semiconductors',                   country: 'United States', beta: 1.10 },
  ORCL:  { sector: 'Technology',  industry: 'Software—Infrastructure',          country: 'United States', beta: 1.01 },
  ADBE:  { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 1.22 },
  CRM:   { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 1.18 },
  AMD:   { sector: 'Technology',  industry: 'Semiconductors',                   country: 'United States', beta: 1.73 },
  INTC:  { sector: 'Technology',  industry: 'Semiconductors',                   country: 'United States', beta: 0.77 },
  QCOM:  { sector: 'Technology',  industry: 'Semiconductors',                   country: 'United States', beta: 1.16 },
  TXN:   { sector: 'Technology',  industry: 'Semiconductors',                   country: 'United States', beta: 1.18 },
  MU:    { sector: 'Technology',  industry: 'Semiconductors',                   country: 'United States', beta: 1.38 },
  ARM:   { sector: 'Technology',  industry: 'Semiconductors',                   country: 'United Kingdom',beta: 1.50 },
  INTU:  { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 1.21 },
  AMAT:  { sector: 'Technology',  industry: 'Semiconductor Equipment & Materials', country: 'United States', beta: 1.42 },
  LRCX:  { sector: 'Technology',  industry: 'Semiconductor Equipment & Materials', country: 'United States', beta: 1.45 },
  KLAC:  { sector: 'Technology',  industry: 'Semiconductor Equipment & Materials', country: 'United States', beta: 1.35 },
  MRVL:  { sector: 'Technology',  industry: 'Semiconductors',                   country: 'United States', beta: 1.48 },
  PANW:  { sector: 'Technology',  industry: 'Software—Infrastructure',          country: 'United States', beta: 1.04 },
  CRWD:  { sector: 'Technology',  industry: 'Software—Infrastructure',          country: 'United States', beta: 1.15 },
  SNOW:  { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 1.02 },
  NOW:   { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 1.07 },
  NET:   { sector: 'Technology',  industry: 'Software—Infrastructure',          country: 'United States', beta: 0.85 },
  PLTR:  { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 2.44 },
  DDOG:  { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 1.10 },
  ZS:    { sector: 'Technology',  industry: 'Software—Infrastructure',          country: 'United States', beta: 0.96 },
  FTNT:  { sector: 'Technology',  industry: 'Software—Infrastructure',          country: 'United States', beta: 1.09 },
  TTD:   { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 1.62 },
  SHOP:  { sector: 'Technology',  industry: 'Software—Application',             country: 'Canada',        beta: 1.54 },
  NFLX:  { sector: 'Communication Services', industry: 'Entertainment',         country: 'United States', beta: 1.37 },
  UBER:  { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 1.26 },
  DASH:  { sector: 'Technology',  industry: 'Software—Application',             country: 'United States', beta: 1.55 },

  // Healthcare
  UNH:   { sector: 'Healthcare', industry: 'Healthcare Plans',                  country: 'United States', beta: 0.52 },
  LLY:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General',        country: 'United States', beta: 0.51 },
  JNJ:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General',        country: 'United States', beta: 0.44 },
  MRK:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General',        country: 'United States', beta: 0.38 },
  ABBV:  { sector: 'Healthcare', industry: 'Drug Manufacturers—General',        country: 'United States', beta: 0.45 },
  TMO:   { sector: 'Healthcare', industry: 'Diagnostics & Research',            country: 'United States', beta: 0.58 },
  ABT:   { sector: 'Healthcare', industry: 'Medical Devices',                   country: 'United States', beta: 0.64 },
  BSX:   { sector: 'Healthcare', industry: 'Medical Devices',                   country: 'United States', beta: 0.82 },
  ELV:   { sector: 'Healthcare', industry: 'Healthcare Plans',                  country: 'United States', beta: 0.60 },
  MDT:   { sector: 'Healthcare', industry: 'Medical Devices',                   country: 'United States', beta: 0.65 },
  ISRG:  { sector: 'Healthcare', industry: 'Medical Devices',                   country: 'United States', beta: 0.76 },
  HCA:   { sector: 'Healthcare', industry: 'Medical Care Facilities',           country: 'United States', beta: 0.85 },
  HUM:   { sector: 'Healthcare', industry: 'Healthcare Plans',                  country: 'United States', beta: 0.62 },
  IDXX:  { sector: 'Healthcare', industry: 'Diagnostics & Research',            country: 'United States', beta: 0.74 },
  VRTX:  { sector: 'Healthcare', industry: 'Biotechnology',                     country: 'United States', beta: 0.52 },
  REGN:  { sector: 'Healthcare', industry: 'Biotechnology',                     country: 'United States', beta: 0.40 },
  MRNA:  { sector: 'Healthcare', industry: 'Biotechnology',                     country: 'United States', beta: 1.38 },
  GILD:  { sector: 'Healthcare', industry: 'Biotechnology',                     country: 'United States', beta: 0.38 },
  BMY:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General',        country: 'United States', beta: 0.30 },
  PFE:   { sector: 'Healthcare', industry: 'Drug Manufacturers—General',        country: 'United States', beta: 0.52 },
  ZTS:   { sector: 'Healthcare', industry: 'Drug Manufacturers—Specialty & Generic', country: 'United States', beta: 0.78 },
  DXCM:  { sector: 'Healthcare', industry: 'Medical Devices',                   country: 'United States', beta: 1.28 },
  IQV:   { sector: 'Healthcare', industry: 'Diagnostics & Research',            country: 'United States', beta: 0.98 },
  MOH:   { sector: 'Healthcare', industry: 'Healthcare Plans',                  country: 'United States', beta: 0.55 },
  CI:    { sector: 'Healthcare', industry: 'Healthcare Plans',                  country: 'United States', beta: 0.56 },

  // Financial Services
  JPM:   { sector: 'Financial Services', industry: 'Banks—Diversified',            country: 'United States', beta: 1.10 },
  V:     { sector: 'Financial Services', industry: 'Credit Services',              country: 'United States', beta: 0.92 },
  MA:    { sector: 'Financial Services', industry: 'Credit Services',              country: 'United States', beta: 1.00 },
  BAC:   { sector: 'Financial Services', industry: 'Banks—Diversified',            country: 'United States', beta: 1.38 },
  GS:    { sector: 'Financial Services', industry: 'Capital Markets',              country: 'United States', beta: 1.42 },
  MS:    { sector: 'Financial Services', industry: 'Capital Markets',              country: 'United States', beta: 1.44 },
  WFC:   { sector: 'Financial Services', industry: 'Banks—Diversified',            country: 'United States', beta: 1.29 },
  BLK:   { sector: 'Financial Services', industry: 'Asset Management',             country: 'United States', beta: 1.31 },
  C:     { sector: 'Financial Services', industry: 'Banks—Diversified',            country: 'United States', beta: 1.56 },
  AXP:   { sector: 'Financial Services', industry: 'Credit Services',              country: 'United States', beta: 1.14 },
  USB:   { sector: 'Financial Services', industry: 'Banks—Diversified',            country: 'United States', beta: 0.90 },
  ICE:   { sector: 'Financial Services', industry: 'Financial Data & Stock Exchanges', country: 'United States', beta: 0.98 },
  CB:    { sector: 'Financial Services', industry: 'Insurance—Property & Casualty',country: 'United States', beta: 0.63 },
  SPGI:  { sector: 'Financial Services', industry: 'Financial Data & Stock Exchanges', country: 'United States', beta: 1.08 },
  MCO:   { sector: 'Financial Services', industry: 'Financial Data & Stock Exchanges', country: 'United States', beta: 1.06 },
  SCHW:  { sector: 'Financial Services', industry: 'Capital Markets',              country: 'United States', beta: 1.22 },
  COF:   { sector: 'Financial Services', industry: 'Credit Services',              country: 'United States', beta: 1.44 },
  BX:    { sector: 'Financial Services', industry: 'Asset Management',             country: 'United States', beta: 1.58 },
  KKR:   { sector: 'Financial Services', industry: 'Asset Management',             country: 'United States', beta: 1.60 },
  APO:   { sector: 'Financial Services', industry: 'Asset Management',             country: 'United States', beta: 1.55 },

  // Consumer Cyclical
  HD:    { sector: 'Consumer Cyclical',   industry: 'Home Improvement Retail',      country: 'United States', beta: 1.04 },
  TGT:   { sector: 'Consumer Defensive',  industry: 'Discount Stores',              country: 'United States', beta: 0.68 },
  DIS:   { sector: 'Communication Services', industry: 'Entertainment',             country: 'United States', beta: 1.18 },
  SBUX:  { sector: 'Consumer Cyclical',   industry: 'Restaurants',                  country: 'United States', beta: 1.08 },
  NKE:   { sector: 'Consumer Cyclical',   industry: 'Footwear & Accessories',       country: 'United States', beta: 0.80 },
  LOW:   { sector: 'Consumer Cyclical',   industry: 'Home Improvement Retail',      country: 'United States', beta: 1.08 },
  MCD:   { sector: 'Consumer Cyclical',   industry: 'Restaurants',                  country: 'United States', beta: 0.72 },
  CMG:   { sector: 'Consumer Cyclical',   industry: 'Restaurants',                  country: 'United States', beta: 1.08 },
  BKNG:  { sector: 'Consumer Cyclical',   industry: 'Travel Services',              country: 'United States', beta: 1.30 },
  ABNB:  { sector: 'Consumer Cyclical',   industry: 'Travel Services',              country: 'United States', beta: 1.44 },
  LYFT:  { sector: 'Consumer Cyclical',   industry: 'Rental & Leasing Services',    country: 'United States', beta: 1.68 },
  GM:    { sector: 'Consumer Cyclical',   industry: 'Auto Manufacturers',           country: 'United States', beta: 1.28 },
  F:     { sector: 'Consumer Cyclical',   industry: 'Auto Manufacturers',           country: 'United States', beta: 1.38 },
  RIVN:  { sector: 'Consumer Cyclical',   industry: 'Auto Manufacturers',           country: 'United States', beta: 2.42 },

  // Communication Services
  CMCSA: { sector: 'Communication Services', industry: 'Telecom Services',          country: 'United States', beta: 0.80 },
  VZ:    { sector: 'Communication Services', industry: 'Telecom Services',          country: 'United States', beta: 0.38 },
  T:     { sector: 'Communication Services', industry: 'Telecom Services',          country: 'United States', beta: 0.54 },
  TMUS:  { sector: 'Communication Services', industry: 'Telecom Services',          country: 'United States', beta: 0.56 },
  CHTR:  { sector: 'Communication Services', industry: 'Telecom Services',          country: 'United States', beta: 0.92 },
  RBLX:  { sector: 'Communication Services', industry: 'Electronic Gaming & Multimedia', country: 'United States', beta: 2.04 },
  SNAP:  { sector: 'Communication Services', industry: 'Internet Content & Information', country: 'United States', beta: 1.52 },
  PINS:  { sector: 'Communication Services', industry: 'Internet Content & Information', country: 'United States', beta: 1.48 },
  SPOT:  { sector: 'Communication Services', industry: 'Entertainment',             country: 'Sweden',        beta: 1.42 },

  // Industrials
  CAT:   { sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery',  country: 'United States', beta: 1.10 },
  DE:    { sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery',  country: 'United States', beta: 1.16 },
  HON:   { sector: 'Industrials', industry: 'Conglomerates',                        country: 'United States', beta: 0.86 },
  MMM:   { sector: 'Industrials', industry: 'Conglomerates',                        country: 'United States', beta: 0.98 },
  GE:    { sector: 'Industrials', industry: 'Aerospace & Defense',                  country: 'United States', beta: 1.12 },
  LMT:   { sector: 'Industrials', industry: 'Aerospace & Defense',                  country: 'United States', beta: 0.52 },
  RTX:   { sector: 'Industrials', industry: 'Aerospace & Defense',                  country: 'United States', beta: 0.70 },
  UPS:   { sector: 'Industrials', industry: 'Integrated Freight & Logistics',       country: 'United States', beta: 0.88 },
  FDX:   { sector: 'Industrials', industry: 'Integrated Freight & Logistics',       country: 'United States', beta: 1.08 },
  UNP:   { sector: 'Industrials', industry: 'Railroads',                            country: 'United States', beta: 0.96 },
  WM:    { sector: 'Industrials', industry: 'Waste Management',                     country: 'United States', beta: 0.84 },
  EMR:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery',       country: 'United States', beta: 1.02 },
  ETN:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery',       country: 'United States', beta: 1.12 },
  PH:    { sector: 'Industrials', industry: 'Specialty Industrial Machinery',       country: 'United States', beta: 1.18 },
  ROK:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery',       country: 'United States', beta: 1.22 },
  ITW:   { sector: 'Industrials', industry: 'Specialty Industrial Machinery',       country: 'United States', beta: 0.96 },
  AXON:  { sector: 'Industrials', industry: 'Aerospace & Defense',                  country: 'United States', beta: 0.88 },

  // Energy
  XOM:   { sector: 'Energy', industry: 'Oil & Gas Integrated',               country: 'United States', beta: 0.92 },
  CVX:   { sector: 'Energy', industry: 'Oil & Gas Integrated',               country: 'United States', beta: 0.96 },
  COP:   { sector: 'Energy', industry: 'Oil & Gas E&P',                      country: 'United States', beta: 1.08 },
  EOG:   { sector: 'Energy', industry: 'Oil & Gas E&P',                      country: 'United States', beta: 1.14 },
  SLB:   { sector: 'Energy', industry: 'Oil & Gas Equipment & Services',     country: 'United States', beta: 1.34 },
  HAL:   { sector: 'Energy', industry: 'Oil & Gas Equipment & Services',     country: 'United States', beta: 1.48 },
  MPC:   { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing',     country: 'United States', beta: 1.22 },
  VLO:   { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing',     country: 'United States', beta: 1.18 },
  PSX:   { sector: 'Energy', industry: 'Oil & Gas Refining & Marketing',     country: 'United States', beta: 1.04 },
  WMB:   { sector: 'Energy', industry: 'Oil & Gas Midstream',                country: 'United States', beta: 1.10 },

  // Basic Materials
  LIN:   { sector: 'Basic Materials', industry: 'Specialty Chemicals',       country: 'United States', beta: 0.72 },
  FCX:   { sector: 'Basic Materials', industry: 'Copper',                    country: 'United States', beta: 1.52 },
  NEM:   { sector: 'Basic Materials', industry: 'Gold',                      country: 'United States', beta: 0.98 },
  ALB:   { sector: 'Basic Materials', industry: 'Specialty Chemicals',       country: 'United States', beta: 1.62 },
  APD:   { sector: 'Basic Materials', industry: 'Specialty Chemicals',       country: 'United States', beta: 0.88 },
  SHW:   { sector: 'Basic Materials', industry: 'Specialty Chemicals',       country: 'United States', beta: 0.92 },
  CF:    { sector: 'Basic Materials', industry: 'Agricultural Inputs',       country: 'United States', beta: 1.28 },

  // Real Estate
  SPG:   { sector: 'Real Estate', industry: 'REIT—Retail',                  country: 'United States', beta: 1.38 },
  PLD:   { sector: 'Real Estate', industry: 'REIT—Industrial',              country: 'United States', beta: 0.96 },
  AMT:   { sector: 'Real Estate', industry: 'REIT—Specialty',               country: 'United States', beta: 0.82 },
  EQIX:  { sector: 'Real Estate', industry: 'REIT—Specialty',               country: 'United States', beta: 0.82 },
  CCI:   { sector: 'Real Estate', industry: 'REIT—Specialty',               country: 'United States', beta: 0.72 },
  O:     { sector: 'Real Estate', industry: 'REIT—Retail',                  country: 'United States', beta: 0.78 },
  WELL:  { sector: 'Real Estate', industry: 'REIT—Healthcare Facilities',   country: 'United States', beta: 0.82 },
  AVB:   { sector: 'Real Estate', industry: 'REIT—Residential',             country: 'United States', beta: 0.88 },

  // Utilities
  NEE:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric',   country: 'United States', beta: 0.56 },
  SO:    { sector: 'Utilities', industry: 'Utilities—Regulated Electric',   country: 'United States', beta: 0.50 },
  DUK:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric',   country: 'United States', beta: 0.42 },
  AEP:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric',   country: 'United States', beta: 0.46 },
  EXC:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric',   country: 'United States', beta: 0.56 },
  D:     { sector: 'Utilities', industry: 'Utilities—Regulated Electric',   country: 'United States', beta: 0.44 },
  SRE:   { sector: 'Utilities', industry: 'Utilities—Regulated Electric',   country: 'United States', beta: 0.56 },

  // Consumer Defensive
  WMT:   { sector: 'Consumer Defensive', industry: 'Discount Stores',        country: 'United States', beta: 0.54 },
  COST:  { sector: 'Consumer Defensive', industry: 'Discount Stores',        country: 'United States', beta: 0.72 },
  PG:    { sector: 'Consumer Defensive', industry: 'Household & Personal Products', country: 'United States', beta: 0.48 },
  KO:    { sector: 'Consumer Defensive', industry: 'Beverages—Non-Alcoholic', country: 'United States', beta: 0.54 },
  PEP:   { sector: 'Consumer Defensive', industry: 'Beverages—Non-Alcoholic', country: 'United States', beta: 0.52 },
  MO:    { sector: 'Consumer Defensive', industry: 'Tobacco',                 country: 'United States', beta: 0.64 },
  PM:    { sector: 'Consumer Defensive', industry: 'Tobacco',                 country: 'United States', beta: 0.64 },
  CL:    { sector: 'Consumer Defensive', industry: 'Household & Personal Products', country: 'United States', beta: 0.44 },
  GIS:   { sector: 'Consumer Defensive', industry: 'Packaged Foods',          country: 'United States', beta: 0.38 },
  HSY:   { sector: 'Consumer Defensive', industry: 'Confectioners',           country: 'United States', beta: 0.36 },
  MDLZ:  { sector: 'Consumer Defensive', industry: 'Confectioners',           country: 'United States', beta: 0.56 },
  WBA:   { sector: 'Consumer Defensive', industry: 'Pharmaceutical Retailers', country: 'United States', beta: 0.48 },

  // Fintech / Growth
  SQ:    { sector: 'Financial Services', industry: 'Software—Application',   country: 'United States', beta: 2.28 },
  PYPL:  { sector: 'Financial Services', industry: 'Credit Services',        country: 'United States', beta: 1.72 },
  COIN:  { sector: 'Financial Services', industry: 'Capital Markets',        country: 'United States', beta: 3.18 },
  HOOD:  { sector: 'Financial Services', industry: 'Capital Markets',        country: 'United States', beta: 2.24 },
  SOFI:  { sector: 'Financial Services', industry: 'Banks—Regional',         country: 'United States', beta: 1.88 },
  AFRM:  { sector: 'Financial Services', industry: 'Credit Services',        country: 'United States', beta: 2.44 },
  NU:    { sector: 'Financial Services', industry: 'Banks—Diversified',      country: 'Brazil',        beta: 1.48 },
  MELI:  { sector: 'Consumer Cyclical',  industry: 'Internet Retail',        country: 'Uruguay',       beta: 1.56 },

  // International ADRs
  TSM:   { sector: 'Technology',  industry: 'Semiconductors',                country: 'Taiwan',        beta: 0.96 },
  ASML:  { sector: 'Technology',  industry: 'Semiconductor Equipment & Materials', country: 'Netherlands', beta: 1.18 },
  NVO:   { sector: 'Healthcare',  industry: 'Drug Manufacturers—General',    country: 'Denmark',       beta: 0.52 },
  SAP:   { sector: 'Technology',  industry: 'Software—Application',          country: 'Germany',       beta: 0.82 },
  TM:    { sector: 'Consumer Cyclical', industry: 'Auto Manufacturers',      country: 'Japan',         beta: 0.62 },
  BABA:  { sector: 'Consumer Cyclical', industry: 'Internet Retail',         country: 'China',         beta: 0.64 },
  JD:    { sector: 'Consumer Cyclical', industry: 'Internet Retail',         country: 'China',         beta: 0.60 },
  SE:    { sector: 'Consumer Cyclical', industry: 'Internet Retail',         country: 'Singapore',     beta: 0.98 },

  // ETFs (no fundamental sector)
  SPY:   { sector: 'ETF', industry: 'S&P 500',  country: 'United States', beta: 1.00 },
  QQQ:   { sector: 'ETF', industry: 'NASDAQ-100',country: 'United States', beta: 1.08 },
  IWM:   { sector: 'ETF', industry: 'Russell 2000', country: 'United States', beta: 1.14 },
  DIA:   { sector: 'ETF', industry: 'Dow Jones', country: 'United States', beta: 0.96 },
  GLD:   { sector: 'ETF', industry: 'Gold',      country: 'United States', beta: 0.18 },
};
